# Generated by Django 4.1.3 on 2023-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='bio',
            field=models.CharField(max_length=250, verbose_name='Расскажите о себе'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='аватар'),
        ),
    ]
