# Generated by Django 4.1.3 on 2023-03-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(choices=[('FAN', 'фэнтези'), ('STU', 'учебники'), ('FIC', 'научная фантастика'), ('SCI', 'научная литература'), ('DIC', 'словари, справочники и тд')], default='STU', max_length=3, verbose_name='теги'),
        ),
        migrations.AlterField(
            model_name='news',
            name='article',
            field=models.CharField(max_length=100, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news_images/default_news.jpg', upload_to='news_images/', verbose_name='Обложка'),
        ),
    ]
