# Generated by Django 4.1.3 on 2023-03-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='quality',
            field=models.CharField(choices=[('VBA', 'книга испорчена'), ('BAD', 'ветхая, будьте осторожны'), ('NOR', 'неплохая, но уже не новая'), ('ANE', 'почти новая'), ('NEW', 'новая')], default='NOR', max_length=3, verbose_name='качество книги'),
        ),
    ]
