# Generated by Django 4.1.3 on 2023-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_in',
            field=models.CharField(choices=[('yes', 'есть в библиотеке'), ('no', 'нет в библиотеке')], default='yes', max_length=30, verbose_name='качество книги'),
        ),
    ]
