# Generated by Django 4.1.3 on 2023-03-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_is_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_in',
            field=models.CharField(choices=[('yes', 'есть в библиотеке'), ('no', 'нет в библиотеке')], default='yes', max_length=30, verbose_name='Наличие книги'),
        ),
        migrations.AlterField(
            model_name='news',
            name='quality',
            field=models.CharField(choices=[('VBA', 'книга испорчена'), ('BAD', 'ветхая, будьте осторожны'), ('NOR', 'неплохая, но уже не новая'), ('ANE', 'почти новая'), ('NEW', 'новая')], default='NOR', max_length=3, verbose_name='Качество книги'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(choices=[('FAN', 'фэнтези'), ('STU', 'учебники'), ('FIC', 'научная фантастика'), ('SCI', 'научная литература'), ('DIC', 'словари, справочники и тд')], default='STU', max_length=3, verbose_name='Тег'),
        ),
    ]
